package com.toniousli.wearablenotes.data;

import android.os.Bundle;

import com.j256.ormlite.field.DataType;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import java.util.Date;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
@DatabaseTable(tableName = "notes")
public class Note {

    public static String ACTION_SHOW = "show";
    public static String EXTRA_NOTE = "note";

    // id is generated by the database and set on the object automagically
    static final String NOTE_FIELD_ID = "id";
    @DatabaseField(generatedId = true, index = true, columnName = NOTE_FIELD_ID)
    private int id;

    static final String NOTE_FIELD_TITLE = "title";
    @DatabaseField(canBeNull = false, dataType= DataType.LONG_STRING, columnName = NOTE_FIELD_TITLE)
    private String title;

    static final String NOTE_FIELD_TEXT = "text";
    @DatabaseField(dataType = DataType.LONG_STRING, columnName = NOTE_FIELD_TEXT)
    private String text;

    static final String NOTE_FIELD_DONE = "done";
    @DatabaseField(dataType = DataType.BOOLEAN, columnName = NOTE_FIELD_DONE)
    private boolean done;

    static final String NOTE_FIELD_DATE = "date";
    @DatabaseField(dataType = DataType.DATE_LONG, columnName = NOTE_FIELD_DATE)
    private Date date;

    public Note() {
        // needed by ormlite
    }

    public Note(String title, String text) {
        this.title = title;
        this.text = text;
        this.done = false;
        this.date = new Date();
    }

    public int getId() {
        return id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getTitle() {
        return title;
    }

    public String getText() {
        return text;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("id=").append(this.id);
        sb.append(", ").append("title=").append(this.title);
        sb.append(", ").append("text=").append(this.text);
        return sb.toString();
    }

    public Bundle toBundle() {
        Bundle bundle = new Bundle();
        bundle.putInt(NOTE_FIELD_ID, getId());
        bundle.putString(NOTE_FIELD_TITLE, getTitle());
        bundle.putString(NOTE_FIELD_TEXT, getText());
        return bundle;
    }

    public static Note fromBundle(Bundle bundle) {
        Note note = new Note();
        note.id = bundle.getInt(Note.NOTE_FIELD_ID);
        note.title = bundle.getString(Note.NOTE_FIELD_TITLE);
        note.text = bundle.getString(Note.NOTE_FIELD_TEXT);
        return note;
    }
}
